plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

group 'com.bazle.vpn_connection_detector'
version '1.0-SNAPSHOT'

android {
    namespace 'com.bazle.vpn_connection_detector'
    compileSdk 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdk 21
    }
}
